apiVersion: v2
name: bw-echo
description: A Helm chart for bw-echo REST API service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - echo
  - api
  - rest
maintainers:
  - name: Vodafone Team
